
import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="bg-slate-900 border-t border-slate-800 mt-12">
      <div className="container mx-auto px-4 py-6 text-center text-slate-500">
        <p>&copy; {new Date().getFullYear()} AI Fitness Coach India. All Rights Reserved.</p>
        <p className="text-xs mt-1">Generated by a world-class AI for personalized fitness.</p>
      </div>
    </footer>
  );
};

export default Footer;
